import randRow from './randRow'
import uuid from './uuid'
const m = [
	'Du spürst eine warme Energie – deine Wunden heilen sich!',
	'Ein Lichtstrahl trifft dich. Du fühlst dich plötzlich stärker.',
	'Du findest einen geheimen Pfadder dir Zeit erspart.',
	'Ein freundlicher Geist überreicht dir ein Geschenk.',
	'Ein alter Zauber wurde aufgelöst – du fühlst dich erleichtert.',
	'Die Sonne bricht durch die Wolken und füllt dich mit Hoffnung.',
	'Du entdeckst eine Quelle reiner Magie – deine Kraft ist erneuert.',
	'Ein Reisender segnet dich mit Glück auf deinem Weg.',
	'Ein altes Lied erklingt – du fühlst dich inspiriert.',
	'Ein Schutzkreis schützt dich vor dem nächsten Schaden.',
	'Du wirst mit einer Vision der Zukunft erfüllt – und fühlst dich vorbereitet.',
	'Du erhältst einen geheimen Segen – deine nächste Begegnung wird einfacher.',
	'Ein Vogel bringt dir eine wertvolle Nachricht.',
	'Du findest einen alten Brief – er stärkt deinen Mut.',
	'Deine Sinne schärfen sich – du erkennst eine Gefahr im Voraus.',
	'Ein plötzlicher Schatten streift dich – du verlierst Lebensenergie.',
	'Du trittst in eine Falle und verletzt dich.',
	'Ein magischer Sturm trifft dich mit voller Wucht.',
	'Deine Tasche ist beschädigt – einige Gegenstände sind verloren.',
	'Eine dunkle Präsenz raubt dir deine Kraft.',
	'Du wirst von seltsamen Stimmen heimgesucht – deine Moral sinkt.',
	'Dein Weg wird durch unheimliche Kreaturen blockiert.',
	'Ein Dieb stiehlt dir unbemerkt etwas aus deinem Inventar.',
	'Du verlierst die Orientierung in dichtem Nebel.',
	'Ein Bann lähmt dich vorübergehend.',
	'Dein Feuerholz ist nass – du kannst kein Lager machen.',
	'Ein bösartiger Blick lähmt dich mit Angst.',
	'Du stürzt in ein Erdloch und verletzt dich am Bein.',
	'Dein Amulett zerbricht – ein Teil deiner Macht geht verloren.',
	'Ein alter Fluch aktiviert sich plötzlich.',
	'Sei vorsichtigFremder. Nicht alles ist so friedlich',
	'Ich habe Geschichten gehört von einem Schatz tief im Osten.',
	'Du erinnerst mich an jemanden... einen alten Helden vielleicht.',
	'Meine Katze ist verschwunden. Wenn du sie findestbekommst du eine Belohnung.',
	'Man sagtdie Sterne flüstern mit jenen',
	'Schau dich gut um. Manchmal versteckt sich das Wertvollste direkt vor deinen Augen.',
	'Die Dunkelheit wächst. Pass auf dich auf da draußen.',
	'Wenn du nach Süden gehstnimm genügend Tränke mit.',
	'Ich war einst Abenteurer wie du – bis ich ein Schwert im Knie hatte.',
	'Hast du etwas zu handeln? Ich suche besondere Materialien.',
	'Hier war früher eine große Stadt... jetzt ist nur noch Stille.',
	'Suchst du Arbeit? Ich habe da etwas für dich... wenn du mutig bist.',
	'Hörst du das? Etwas stimmt nicht mit diesem Ort.',
	'Der Fluss spricht. Hast du es bemerkt?',
	'Einmal war ich auf der anderen Seite der Berge – dort gibt es Wunder.',
	'Ein Schatten bewegt sich – bereite dich auf den Kampf vor!',
	'Dein Herz schlägt schneller – ein Gegner nähert sich!',
	'Du hast den falschen Pfad gewählt!ruft dein Feind.',
	'Dein Gegner zieht seine Waffe. Keine Gnade!',
	'Du spürst feindliche Präsenz – der Kampf beginnt.',
	'Das wird dir noch leid tun!schreit dein Widersacher.',
	'Ein Geräusch hinter dir – du wirst angegriffen!',
	'Endlich ein würdiger Gegner!ruft der Feind.',
	'Der Boden zittert – etwas Großes nähert sich.',
	'Dein Instinkt war richtig – du bist nicht allein.',
	'Du fühlst dich stärker – du bist aufgestiegen!',
	'Ein neues Level! Neue Kräfte erwachen in dir.',
	'Dein Training zahlt sich aus – du bist gewachsen.',
	'Du meisterst eine neue Fähigkeit.',
	'Ein Licht durchdringt dich – du hast ein Level erreicht.',
	'Dein Körper pulsiert vor Energie – Level Up!',
	'Erfahrung macht dich weiser – du bist bereit für mehr.',
	'Die Luft um dich vibriert – du entwickelst dich weiter.',
	'Du bist nun mächtiger als je zuvor.',
	'Gut gemacht!hörst du eine Stimme in deinem Inneren.',
	'Du hast einen neuen Auftrag erhalten.',
	'Die Aufgabe ist abgeschlossen – kehre zum Auftraggeber zurück.',
	'Ein Tagebucheintrag wurde aktualisiert.',
	'Dein Fortschritt wurde gespeichert.',
	'Du findest einen Hinweis auf das nächste Ziel.',
	'Etwas stimmt nicht... die Quest entwickelt sich anders.',
	'Ein neuer Ort wurde auf deiner Karte markiert.',
	'Ein alter Bekannter hat dir eine neue Mission gegeben.',
	'Du brauchst ein besonderes Item für diese Aufgabe.',
	'Die Belohnung für diese Aufgabe wartet auf dich.',
	'Die Bäume flüstern im Wind – etwas Altes lebt noch hier.',
	'Ein ferner Donner hallt durch die Berge.',
	'Im Dunst der Ebene liegt ein Geruch von Asche.',
	'Ein Stern fällt langsam vom Himmel – leuchtend wie ein Traum.',
	'Das Wasser spiegelt eine andere Welt.',
	'Ein leises Flüstern begleitet dich durch die Höhle.',
	'Der Wind trägt vergessene Lieder zu dir.',
	'Dein Schatten scheint sich anders zu bewegen...',
	'Der Boden knirscht – war da etwas unter der Erde?',
	'Nebel zieht über das Land – die Sicht ist eingeschränkt.'
]
const t = ['default', 'primary', 'info', 'success', 'danger', 'warning']
const getMsg = () => {
	const id = uuid()
	const type = randRow(t)
	const message = randRow(m)
	return { id, type, message }
}

export default getMsg
